# Agent推理配置
agent:
  max_iterations: 40
  # 是否引入校准
  open_calibration: true
  # 是否引入语义结果
  open_semantic: true
  # 是否引入专家分析
  open_expert: true
  # 是否引入执行聚类
  open_clustering: true
  agent_template: "./forensic_agent/configs/agent_template.txt"
  reporter:
    prompt_path: "./forensic_agent/configs/prompts/reporter_prompt.txt"
  # save_dir: "./outputs/agent_results_confuse_qwen3[DRCT]"
  save_dir: "./outputs/agent_results_confuse_qwen3"
  expert_models: 
    - "DRCT"
    - "PatchShuffle"
    - "SPAI"
    - "RINE"
    

# LLM配置 - Agent推理引擎
llm:
  model: "z-uo/qwen2.5vl_tools:32b"
  base_url:
    - "http://localhost:11435"
    - "http://localhost:11436"
    - "http://localhost:11437"
    - "http://localhost:11438"
    - "http://localhost:11439"
    - "http://localhost:11440"
    - "http://localhost:11441"
    - "http://localhost:11442"

    - "http://172.31.224.52:11435"
    - "http://172.31.224.52:11436"
    - "http://172.31.224.52:11437"
    - "http://172.31.224.52:11438"
    - "http://172.31.224.52:11439"
    - "http://172.31.224.52:11440"
    - "http://172.31.224.52:11441"
    - "http://172.31.224.52:11442"

    - "http://172.31.220.65:11435"
    - "http://172.31.220.65:11436"
    - "http://172.31.220.65:11437"
    - "http://172.31.220.65:11438"
    - "http://172.31.220.65:11439"
    - "http://172.31.220.65:11440"
    - "http://172.31.220.65:11441"
    - "http://172.31.220.65:11442"

    - "http://172.31.220.66:11435"
    - "http://172.31.220.66:11436"
    - "http://172.31.220.66:11437"
    - "http://172.31.220.66:11438"
    - "http://172.31.220.66:11439"
    - "http://172.31.220.66:11440"
    - "http://172.31.220.66:11441"
    - "http://172.31.220.66:11442"

    - "http://172.31.220.69:11435"
    - "http://172.31.220.69:11436"
    - "http://172.31.220.69:11437"
    - "http://172.31.220.69:11438"
    - "http://172.31.220.69:11439"
    - "http://172.31.220.69:11440"
    - "http://172.31.220.69:11441"
    - "http://172.31.220.69:11442"
  model_provider: "Ollama"
  stream: false
  reasoning: false
  seed: 42
  num_ctx: 32000
  temperature: 0
  support_vision: true

# llm:
#   model: "gpt-4o"
#   # api_key: ""
#   # base_url: "https://api.apiyi.com"
#   base_url: "https://api.csun.site"
#   api_key: ""
#   temperature: 0 # 设置0.1以确保结果更稳定
#   timeout: 60
#   model_provider: "OpenAI"

# 日志配置
logging:
  level: "INFO"
  format: "detailed"
  file_path: "./logs/afa.log"
  rotation: "10 MB"
  retention: "7 days"
  compression: "zip"

# 特征提取配置
feature_extraction:
  spatial:
    enable_lbp: true
    enable_glcm: true
    enable_edge: true

  # 多模态特征配置
  frequency:
    enable_fft: true
    enable_dct: true
    enable_wavelet: true
    wavelet_type: "db4"
    wavelet_levels: 3

  # 鲁棒性测试
  noise_robustness:
    enable: true
    noise_types: ["gaussian", "salt_pepper"]
    intensity_range: [0.01, 0.1]

  # 执行图像语义特征模式
  semantic_llm:
    prompt_path: "/data2/yuyangxin/Agent/forensic_agent/configs/prompts/semantic_analysis.txt"

datasets:
  # test_paths: "/data2/yuyangxin/Agent/outputs/dataset_sampling/AIGCDetect-testset_AIGIBench_Chameleon_Community-Forensics-eval_WildRF_WIRA_GenImage-Val/merged_expert_cluster_analysis.csv"
  # test_paths: "/data2/yuyangxin/Agent/outputs/dataset_sampling/AIGCDetect-testset_AIGIBench_Chameleon_Community-Forensics-eval_WildRF_WIRA_GenImage-Val/samples_by_label_with_clusters.csv"
  # test_paths: "/data2/yuyangxin/Agent/outputs/dataset_sampling/AIGCDetect-testset_AIGIBench_Chameleon_Community-Forensics-eval_WildRF_WIRA_GenImage-Val/sample_by_label/test_dataset_['CLIP', 'CFA', 'SRM'].csv"
  # test_paths: "/data2/yuyangxin/Agent/outputs/dataset_sampling/AIGCDetect-testset_AIGIBench_Chameleon_Community-Forensics-eval_WildRF_WIRA_GenImage-Val/sample_by_label/merged_expert_cluster_analysis.csv"
  test_paths: "/data2/yuyangxin/Agent/outputs/x-fuse/test_dataset.csv"

# 工具
tools:
  ExpertAnalysis:
    prompt_path: "./forensic_agent/configs/prompts/expert_analysis_prompt.txt"
  ClusteringAnalysis:
    prompt_path: "./forensic_agent/configs/prompts/cluster_analysis_prompt.txt"
  SemanticAnalysis:
    prompt_path: "./forensic_agent/configs/prompts/forensic_analysis_prompt.txt"

# 模型画像配置
profiles:
  semantic_profiles: "/data2/yuyangxin/Agent/outputs/dataset_sampling/AIGCDetect-testset_AIGIBench_Chameleon_Community-Forensics-eval_WildRF_WIRA_GenImage-Val/sample_by_label/semantic/gpt4o_evaluation_results.json"
  model_profiles: "./forensic_agent/configs/profiles/model_profiles.json"
  clustering_performance_profiles: "/data2/yuyangxin/Agent/outputs/clustering_profiles/GenImage_performance_profiles.json"
  clustering_analysis_profiles: "/data2/yuyangxin/Agent/outputs/clustering_profiles/GenImage_analysis_profiles.json"
  calibration_profiles: "./forensic_agent/configs/profiles/calibration_model_profile_GenImage.json"
