"""Prompt parser helpers for structured VLM outputs.

中文说明: 该模块负责加载提示词、注入格式约束并重试解析 JSON/Pydantic 输出。
English: This module loads prompts, injects format instructions, and retries
JSON/Pydantic parsing for structured VLM outputs.
"""

import json
from abc import ABC
from pathlib import Path

from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.chat_history import BaseChatMessageHistory, InMemoryChatMessageHistory
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_openai import ChatOpenAI
from pydantic import BaseModel
from loguru import logger


class ErrorDetail(BaseModel):
    """Structured parsing failure.

    中文说明: 解析失败时返回错误文本、原始响应和会话历史, 便于上层抛出清晰异常。
    English: On parse failure this carries error text, raw response, and history
    so callers can raise a clear exception.
    """

    error: str
    raw_content: str
    history: list


class BaseParser(ABC):
    """Base parser for prompt + LLM + Pydantic output.

    中文说明: BaseParser 只保存内存会话历史, 不写入磁盘。
    English: BaseParser stores conversation history in memory only and does not
    write it to disk.
    """

    RETRY_PROMPT_TEMPLATE = (
        "An error occurred in the json parsing: '{err_detail}'."
        "Please re-output according to the format instructions. Don't give explanations or wrong answers."
    )

    def __init__(self, llm: ChatOpenAI, prompt_path, pydantic_object=None, store=None):
        """Initialize parser from a prompt file.

        中文说明: prompt_path 可以是绝对/相对路径; 不存在且无后缀时尝试当前目录下同名 txt。
        English: prompt_path can be absolute or relative; if it does not exist
        and has no suffix, a local .txt file is tried.
        """
        prompt_path = Path(prompt_path)
        if prompt_path.exists():
            self.prompt_path = prompt_path
        else:
            if not prompt_path.suffix:
                prompt_path = prompt_path.with_suffix(".txt")
            self.prompt_path = Path(__file__).parent / prompt_path
        assert self.prompt_path.exists(), f"Prompt file [{self.prompt_path}] does not exist"

        self.chat_template = None
        self.llm = llm

        if store is not None:
            self.store = store
        else:
            self.store = {}

        with open(self.prompt_path, "r", encoding="utf-8") as f:
            file_content = f.read()
            sections = file_content.split("###")
            system_msg = sections[-1]

        self.system_msg = system_msg
        self.parser = PydanticOutputParser(pydantic_object=pydantic_object) if pydantic_object else None
        self.template = self.system_template(self.parser)
        self.chain = self.template | self.llm
        self.with_message_history = RunnableWithMessageHistory(self.chain, self.get_session_history)

    def get_session_history(self, session_id: str) -> BaseChatMessageHistory:
        """Return in-memory history for a session.

        中文说明: session_id 基于图片路径 hash, 避免不同样本历史串扰。
        English: session_id is based on the image-path hash to avoid history
        leakage across samples.
        """
        if session_id not in self.store:
            self.store[session_id] = InMemoryChatMessageHistory()
        return self.store[session_id]

    def system_template(self, output_parser: PydanticOutputParser = None):
        """Build the chat prompt template.

        中文说明: format_instructions 由 PydanticOutputParser 自动生成。
        English: format_instructions are generated by PydanticOutputParser.
        """
        placeholders = [
            ("system", self.system_msg),
            ("system", "{format_instructions}"),
            MessagesPlaceholder(variable_name="messages"),
        ]
        # return ChatPromptTemplate(placeholders)
        partial_vars = {"format_instructions": output_parser.get_format_instructions() if output_parser is not None else None}
        return ChatPromptTemplate(placeholders, partial_variables=partial_vars)

    def run(self, inputs: HumanMessage, session_id, max_retries: int = 3, *args, **kwargs) -> BaseModel:
        """Run structured generation with retry.

        中文说明: 若模型输出不是合法 JSON 或无法映射到目标模型, 会追加纠错提示重试。
        English: If model output is not valid JSON or cannot map to the target
        model, a corrective prompt is appended and retried.
        """
        config = {"configurable": {"session_id": f"{session_id}"}}
        human_messages = inputs if isinstance(inputs, list) else [inputs]

        def retry_feedback(err) -> HumanMessage:
            """Build retry feedback.

            中文说明: 同时兼容 Exception 和字符串错误。
            English: Supports both Exception objects and plain error strings.
            """
            if isinstance(err, str):
                err_detail = err
            else:
                err_detail = json.dumps(err.errors(), ensure_ascii=False, indent=2) if hasattr(err, "errors") else str(err)
            retry_prompt = self.RETRY_PROMPT_TEMPLATE.format(err_detail=err_detail)
            return HumanMessage(content=retry_prompt)

        for attempt in range(1, max_retries + 1):
            resp: AIMessage = self.with_message_history.invoke({"messages": human_messages}, config=config)
            resp.content = resp.content.replace("“", '"').replace("”", '"')
            if self.parser is None:
                return resp.content

            try:
                info = resp.content.replace("```json\n", "").replace("```", "").strip()
                json.loads(info)
            except json.JSONDecodeError as e:
                pos = getattr(e, "pos", None)
                msg = getattr(e, "msg", str(e))
                json_decoder_error = f"JSONDecodeError Position: {pos}\nError message: {msg}"
                if attempt < max_retries:
                    human_messages.append(retry_feedback(json_decoder_error))
                    continue
                else:
                    logger.error(f"经过 {max_retries} 次重试仍无法解析对象: {e}, 内容: {resp.content}")
                    ret = {
                        "error": f"经过 {max_retries} 次重试仍无法解析为Json对象",
                        "raw_content": resp.content,
                        "history": self.get_session_history(session_id).messages,
                    }
                    return ErrorDetail(**ret)

            try:
                target = self.parser.parse(resp.content)
                if attempt > 1:
                    try:
                        self.delete_message(session_id, -(2 * (attempt - 1)) - 1, -2)
                    except Exception:
                        logger.exception("删除重试消息失败")
                return target
            except Exception as e:
                if attempt < max_retries:
                    human_messages.append(retry_feedback(e))
                    continue
                else:
                    ret = {
                        "error": f"经过 {max_retries} 次重试仍无法解析为目标实力对象",
                        "raw_content": resp.content,
                        "history": self.get_session_history(session_id).messages,
                    }
                    return ErrorDetail(**ret)

    def run_stream(self, inputs: HumanMessage, max_retries: int = 3):
        """Stream model output and parse at the end.

        中文说明: 最小 CLI 默认不用流式接口, 该方法保留给未来 UI/服务化场景。
        English: The minimal CLI does not use streaming; this method is kept for
        future UI/service use.
        """
        prompt = self.template.format_prompt(input=inputs.content)
        messages = prompt.to_messages()
        if not getattr(self.llm, "streaming", False):
            raise ValueError("请在初始化时设置 ChatOpenAI(streaming=True) 以支持流式传输")
        last_err = None

        for attempt in range(1, max_retries + 1):
            complete_content = ""
            for chunk in self.llm.stream(messages):
                delta = chunk.generations[0].message.content
                complete_content += delta
                yield delta

            messages.append(AIMessage(content=complete_content))
            try:
                parsed = self.parser.parse(complete_content)
                yield parsed
                return
            except Exception as e:
                last_err = e
                if attempt < max_retries:
                    self._add_retry_feedback(messages, e)
                else:
                    raise RuntimeError(f"经过 {max_retries} 次流式重试仍无法解析") from last_err

    def delete_message(self, session_id: str, start_index: int, end_index: int = None):
        """Delete messages from in-memory history.

        中文说明: 仅用于清理重试提示, 不影响磁盘文件。
        English: Used only to clean retry prompts and does not affect disk files.
        """
        history = self.get_session_history(session_id)
        msgs = history.messages  # List[BaseMessage]
        length = len(msgs)

        def norm(i: int) -> int:
            return i if i >= 0 else length + i

        if end_index is None:
            idx = norm(start_index)
            if not (0 <= idx < length):
                raise IndexError(f"消息索引 {start_index} 超出范围")
            del msgs[idx]
        else:
            s = norm(start_index)
            e = norm(end_index)
            if not (0 <= s < length and 0 <= e < length):
                raise IndexError(f"删除范围 [{start_index}, {end_index}] 超出历史消息长度 {length}")
            if s <= e:
                del msgs[s : e + 1]
            else:
                del msgs[e : s + 1]

    def modify_message(
        self,
        session_id: str,
        index: int,
        new_content: str,
    ):
        """Modify one history message and regenerate.

        中文说明: 调试接口, 最小 test 路径不会调用。
        English: Debug helper; the minimal test path does not call it.
        """
        history = self.get_session_history(session_id)
        msgs = history.messages  # List[BaseMessage]

        if not (0 <= index < len(msgs)):
            raise IndexError(f"消息索引 {index} 超出范围")
        orig = msgs[index]
        msgs[index] = HumanMessage(content=new_content) if isinstance(orig, HumanMessage) else AIMessage(content=new_content)

        config = {"configurable": {"session_id": session_id}}
        ai_msg = self.with_message_history.invoke({"messages": msgs}, config=config)

        return self.parser.parse(ai_msg.content)
